# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE forum;" -U postgres
  - psql -c "CREATE USER solomatov WITH PASSWORD '123';" -U postgres
  - psql -c 'CREATE SCHEMA "solomatov" AUTHORIZATION solomatov;' -U postgres -d forum


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на vv.solomatov@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      - vv.solomatov@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
